### ISSUE TITLE
Incorrect input image recieved in component

### ISSUE THREAD

**Issue by Kanav-7** [robocomp/robocomp-robolab#46]
Emotion recognition component was not working as expected. On inspecting the codebase, the following input was being recieved by the component:

![Error](https://user-images.githubusercontent.com/23416069/76364367-fc4f3300-634a-11ea-9dc5-9a84a4f328b1.png)

There seems to be some bug in either sending or receiving of the image. Can anyone look into this?

**Comment by adityaaggarwal97** [comment]
This seems a legit issue. I will look into this and get it resolved

**Comment by orensbruli** [comment]
Thank you @Kanav-7 and Thank you @adityaaggarwal97 for the review.
